/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeSettingsRouteImport } from './routes/$countryCode/settings'
import { Route as CountryCodeQuotesRouteImport } from './routes/$countryCode/quotes'
import { Route as CountryCodeOrdersRouteImport } from './routes/$countryCode/orders'
import { Route as CountryCodeEmployeesRouteImport } from './routes/$countryCode/employees'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeAccountRegisterRouteImport } from './routes/$countryCode/account/register'
import { Route as CountryCodeAccountLoginRouteImport } from './routes/$countryCode/account/login'
import { Route as CountryCodeAccountAcceptInviteRouteImport } from './routes/$countryCode/account/accept-invite'
import { Route as CountryCodeOrderOrderIdPaymentRouteImport } from './routes/$countryCode/order/$orderId/payment'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSettingsRoute = CountryCodeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuotesRoute = CountryCodeQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeOrdersRoute = CountryCodeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeEmployeesRoute = CountryCodeEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountRegisterRoute =
  CountryCodeAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountLoginRoute = CountryCodeAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountAcceptInviteRoute =
  CountryCodeAccountAcceptInviteRouteImport.update({
    id: '/account/accept-invite',
    path: '/account/accept-invite',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdPaymentRoute =
  CountryCodeOrderOrderIdPaymentRouteImport.update({
    id: '/order/$orderId/payment',
    path: '/order/$orderId/payment',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/orders': typeof CountryCodeOrdersRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/settings': typeof CountryCodeSettingsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/orders': typeof CountryCodeOrdersRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/settings': typeof CountryCodeSettingsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/orders': typeof CountryCodeOrdersRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/settings': typeof CountryCodeSettingsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/orders'
    | '/$countryCode/quotes'
    | '/$countryCode/settings'
    | '/$countryCode/store'
    | '/$countryCode/'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/orders'
    | '/$countryCode/quotes'
    | '/$countryCode/settings'
    | '/$countryCode/store'
    | '/$countryCode'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/orders'
    | '/$countryCode/quotes'
    | '/$countryCode/settings'
    | '/$countryCode/store'
    | '/$countryCode/'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HealthRoute: typeof HealthRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/settings': {
      id: '/$countryCode/settings'
      path: '/settings'
      fullPath: '/$countryCode/settings'
      preLoaderRoute: typeof CountryCodeSettingsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes': {
      id: '/$countryCode/quotes'
      path: '/quotes'
      fullPath: '/$countryCode/quotes'
      preLoaderRoute: typeof CountryCodeQuotesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/orders': {
      id: '/$countryCode/orders'
      path: '/orders'
      fullPath: '/$countryCode/orders'
      preLoaderRoute: typeof CountryCodeOrdersRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/employees': {
      id: '/$countryCode/employees'
      path: '/employees'
      fullPath: '/$countryCode/employees'
      preLoaderRoute: typeof CountryCodeEmployeesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/register': {
      id: '/$countryCode/account/register'
      path: '/account/register'
      fullPath: '/$countryCode/account/register'
      preLoaderRoute: typeof CountryCodeAccountRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/login': {
      id: '/$countryCode/account/login'
      path: '/account/login'
      fullPath: '/$countryCode/account/login'
      preLoaderRoute: typeof CountryCodeAccountLoginRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/accept-invite': {
      id: '/$countryCode/account/accept-invite'
      path: '/account/accept-invite'
      fullPath: '/$countryCode/account/accept-invite'
      preLoaderRoute: typeof CountryCodeAccountAcceptInviteRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/payment': {
      id: '/$countryCode/order/$orderId/payment'
      path: '/order/$orderId/payment'
      fullPath: '/$countryCode/order/$orderId/payment'
      preLoaderRoute: typeof CountryCodeOrderOrderIdPaymentRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}

interface CountryCodeRouteChildren {
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeEmployeesRoute: typeof CountryCodeEmployeesRoute
  CountryCodeOrdersRoute: typeof CountryCodeOrdersRoute
  CountryCodeQuotesRoute: typeof CountryCodeQuotesRoute
  CountryCodeSettingsRoute: typeof CountryCodeSettingsRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountAcceptInviteRoute: typeof CountryCodeAccountAcceptInviteRoute
  CountryCodeAccountLoginRoute: typeof CountryCodeAccountLoginRoute
  CountryCodeAccountRegisterRoute: typeof CountryCodeAccountRegisterRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
  CountryCodeOrderOrderIdPaymentRoute: typeof CountryCodeOrderOrderIdPaymentRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeEmployeesRoute: CountryCodeEmployeesRoute,
  CountryCodeOrdersRoute: CountryCodeOrdersRoute,
  CountryCodeQuotesRoute: CountryCodeQuotesRoute,
  CountryCodeSettingsRoute: CountryCodeSettingsRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountAcceptInviteRoute: CountryCodeAccountAcceptInviteRoute,
  CountryCodeAccountLoginRoute: CountryCodeAccountLoginRoute,
  CountryCodeAccountRegisterRoute: CountryCodeAccountRegisterRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
  CountryCodeOrderOrderIdPaymentRoute: CountryCodeOrderOrderIdPaymentRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HealthRoute: HealthRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
